#!/bin/sh
# One-shot local setup and start. Safe to run repeatedly: installs Moodle only
# on the first run, otherwise just (re)builds and (re)starts the stack.
# Engine behind "Setup Moodle.app"; also the CLI entry point.
set -eu

cd "$(dirname "$0")/.."

# The applet's `do shell script` runs with a bare PATH; probe the usual
# Docker Desktop, Homebrew and OrbStack install locations.
for dir in /usr/local/bin /opt/homebrew/bin "$HOME/.orbstack/bin"; do
  if [ -x "$dir/docker" ]; then
    case ":$PATH:" in
      *":$dir:"*) ;;
      *) PATH="$PATH:$dir" ;;
    esac
  fi
done
export PATH

# Progress: the "== " phase lines feed the applet's progress window and the
# terminal/log for CLI users.
phase() {
  echo "== $1"
}

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker not found. Install Docker Desktop (or OrbStack) first." >&2
  exit 1
fi
if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker is not running. Start Docker Desktop (or OrbStack) and try again." >&2
  exit 1
fi

if [ ! -f ./.env ]; then
  phase "Creating a default configuration (.env)."
  cat > ./.env <<'EOF'
# Generated by tools/start.sh with local-use defaults.
# Edit as needed; see .env.example and README.md. Values are read at install
# time; changing them later does not reconfigure an installed site.
MOODLE_HTTP_PORT=8000
MOODLE_SITE_URL=http://localhost:8000
MOODLE_SITE_FULLNAME="Moodle Site"
MOODLE_SITE_SHORTNAME=Moodle
MOODLE_ADMIN_USER=admin
MOODLE_ADMIN_EMAIL=admin@example.com
# Temporary password; Moodle forces a change at first login.
MOODLE_ADMIN_PASSWORD=Change-me!
MOODLE_ADMIN_FORCE_PASSWORD_CHANGE=1
MOODLE_NOREPLY_EMAIL=noreply@example.com

# Finnish is installed alongside English; browsers asking for Finnish get it,
# everything else falls back to MOODLE_LANG.
MOODLE_LANGPACKS=fi
MOODLE_LANG=en

MOODLE_PERSISTENT_ROOT=./.persistent

MARIADB_UID=2001
MARIADB_GID=2001

MOODLE_STACK_MAXIMAVERSION=5.44.0
MOODLE_STACK_MAXIMACOMMAND=
MOODLE_STACK_MAXIMACOMMANDOPT=
MOODLE_STACK_MAXIMACOMMANDSERVER=http://maxima:8080/goemaxima
MOODLE_STACK_MAXIMALIBRARIES="stats, distrib, descriptive"
MOODLE_STACK_PLATFORM="server"
EOF
fi

. ./init/scripts/init-env.sh

root="${MOODLE_PERSISTENT_ROOT:-/srv/moodle-persistent}"
if [ ! -d "$root" ]; then
  mkdir -p "$root/mariadb" "$root/moodledata" "$root/backups/db"
  # Container uids (www-data, mariadb) must be able to write on Linux hosts.
  chmod -R 777 "$root"
fi

# Pre-create the qbank build dir: the moodle service bind-mounts it, and a
# missing bind-mount source would be created root-owned by dockerd, leaving
# tools/qbank.sh unable to write into it on Linux hosts.
mkdir -p "${QBANK_BUILD_DIR:-./.generated/qbank}"

phase "Building Docker images. The first run downloads a lot; this can take several minutes."
dc build
phase "Starting services."
dc up -d

if [ -f "$root/moodledata/config.php" ]; then
  phase "Moodle is already installed; skipping installation."
else
  phase "Installing Moodle. This takes a few minutes."
  ./init/scripts/moodle-init.sh
fi
phase "Configuring languages."
./init/scripts/lang-init.sh
phase "Configuring STACK."
./init/scripts/stack-init.sh

port="${MOODLE_HTTP_PORT:-8000}"
url="http://localhost:${port}"
i=0
until curl -fsS "${url}/login/index.php" >/dev/null 2>&1; do
  i=$((i+1))
  if [ "$i" -ge 30 ]; then
    echo "ERROR: Moodle did not respond at ${url} within 60 s; see 'docker compose logs moodle'." >&2
    exit 1
  fi
  sleep 2
done

phase "Moodle is ready at ${url}."
if [ -z "${CI:-}" ]; then
  if command -v open >/dev/null 2>&1; then
    open "$url"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url"
  fi
fi
