#!/bin/sh
set -eu

if ! command -v yq >/dev/null 2>&1; then
  echo "ERROR: yq is required. Install it and try again." >&2
  exit 1
fi

if [ ! -f ./versions.yml ]; then
  echo "ERROR: versions.yml not found." >&2
  exit 1
fi

output="${1:-./.env.versions}"
tmp="$(mktemp)"

require_value() {
  key="$1"
  query="$2"
  value="$(yq -r "$query" ./versions.yml)"
  if [ "$value" = "null" ] || [ -z "$value" ]; then
    echo "ERROR: ${key} is missing or empty in versions.yml" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
}

allow_empty() {
  key="$1"
  query="$2"
  value="$(yq -r "$query" ./versions.yml)"
  if [ "$value" = "null" ]; then
    echo "ERROR: ${key} is missing in versions.yml" >&2
    exit 1
  fi
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
}

{
  echo "# Generated by tools/update-versions.sh from versions.yml"
} > "$tmp"

require_value "MOODLE_PHP_BASE_IMAGE" '.moodle_base_image'
require_value "MOODLE_RELEASE_URL" '.moodle_release_url'
require_value "MOODLE_RELEASE_SHA256" '.moodle_release_sha256'
require_value "MARIADB_IMAGE" '.mariadb_image'
require_value "GOEMAXIMA_IMAGE" '.goemaxima_image'
require_value "MOODLE_STACK_PLUGIN_URL" '.stack_plugin_url'
require_value "MOODLE_STACK_PLUGIN_SHA256" '.stack_plugin_sha256'
require_value "MOODLE_STACK_BEHAVIOUR_DFEXPLICIT_URL" '.stack_behaviour_plugin_urls.qbehaviour_dfexplicitvaildate'
allow_empty "MOODLE_STACK_BEHAVIOUR_DFEXPLICIT_SHA256" '.stack_behaviour_plugin_sha256.qbehaviour_dfexplicitvaildate'
require_value "MOODLE_STACK_BEHAVIOUR_DFCBMEXPLICIT_URL" '.stack_behaviour_plugin_urls.qbehaviour_dfcbmexplicitvaildate'
allow_empty "MOODLE_STACK_BEHAVIOUR_DFCBMEXPLICIT_SHA256" '.stack_behaviour_plugin_sha256.qbehaviour_dfcbmexplicitvaildate'
require_value "MOODLE_STACK_BEHAVIOUR_ADAPTIVEMULTIPART_URL" '.stack_behaviour_plugin_urls.qbehaviour_adaptivemultipart'
allow_empty "MOODLE_STACK_BEHAVIOUR_ADAPTIVEMULTIPART_SHA256" '.stack_behaviour_plugin_sha256.qbehaviour_adaptivemultipart'

mv "$tmp" "$output"
